name: chimaera
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python>=3.7
  - matplotlib-base
  - pandas
  - seaborn
  - scipy
  - scikit-image
  - biopython>=1.79
  - cython
  - pip
  - pip:
    - cooler==0.8.11
